Document get model api
CMU-313/fall-22-hw4-team-sweg pull request #21
Opened 2022-11-01 18:35 UTC by jihyoc

## Purpose
This PR resolves #9 by creating `GET /models`. It accepts the `model_id` to get the model and outputs the list of `ModelMetadata` which can be passed on to POST or other calls. 

## Changes
Created `GET /model`

## Additional Comments

2022-11-01 18:36 UTC, jihyoc commented
Im not sure if there needs to be a change in model_metadata.py lmk @kyminbb

2022-11-01 19:39 UTC, kyminbb requested changes

2022-11-01 19:39 UTC, kyminbb commented on app/handlers/models.py
> +    def get(self, model_id: int) -> Dict[str, Any]:
I think `model_id` should be removed so that the API endpoint can fetch a list of all the model metadata.

2022-11-01 19:39 UTC, kyminbb commented on app/handlers/models.py
> +        return ModelService.get_model(model_id)
Likewise, it should call a different function from `ModelService` (ex. `get_model_list`) that returns all the model metadata.

2022-11-02 01:18 UTC, kyminbb approved these changes
LGTM!!

2022-11-02 01:19 UTC, merged